ai/urls.py
from django.urls import path
from . import views

app_name = 'ai'
urlpatterns = [
    path('', views.home, name="homepage"),
    path('upload/', views.upload, name='upload'),
    path('history/', views.history, name='history')
]

riio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ai.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ai/backend/models.py
from django.db import models

# Create your models here.

ai/models.py
from django.db import models

# Create your models here.
from django.db import models


class Profile(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/%Y/%m/%d/', blank=True, null=True)
    result = models.CharField(max_length=50)

    def __str__(self):
        return self.name

ai/forms.py
from django import forms
from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'image']

upload/forms.py
from django import forms
from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'image']

ai/views.py
import os

from django.shortcuts import render

from ai.backend import utils
from .forms import ProfileForm
from .models import Profile


# Create your views here.
def home(request):
    return render(request, "ai/home.html")


def upload(request):
    image = None

    if request.method == 'POST':
        form = ProfileForm(request.POST, files=request.FILES)
        if form.is_valid():
            image = form.save()
        
        # Update image's result
        last_id = Profile.objects.count()
        image = Profile.objects.filter(id=last_id)[0]
        image.result = utils.get_result(
            os.path.join('media', str(image.image)))
        image.save()

    else:
        form = ProfileForm()

    return render(request, 'ai/upload.html', {'form': form, 'image': image})


def history(request):
    images = Profile.objects.order_by('-id')
    return render(request, 'ai/history.html', {'images': images})

templates/ai/history.html
<!DOCTYPE html>
{% load static %}
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<style>
    img {
    max-width: 100%;
    max-height: 100%;
}
.square {
    height: 500px;
    width: 350px;
}
</style>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-xl-12">
            <h1 class="mt-2 text-xl-center font-weight-bold display-3 bg-dark text-white">E.D.I.T.H</h1>
            <hr class="mt-0 mb-4">
            {% block history %}
                <div>
                    {% for image in images %}
                        <div class="d-lg-inline-block col-xl-4 m-xl-5 offset-xl-1 card border-0" style=" width:500px; height: 350px">
                            <img src="{{ image.image.url }}  "class="card-img-top rounded mx-auto d-block p-2 square" style="width:420px;high:420px;" alt="">
                            <div class="card-body">
                                <div class="card-text">
                                        <h3>Name: {{ image.name }}</h3>
                                        <h3>Result: {{ image.result }}</h3>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

templates/ai/home.html
{% extends "base.html" %}
{% block page %}
  <div class="banner">
    <div class="container">
      <div class="callout">
        <div class="intro-text">CLASSIFICATION OF</div>
        <div class="intro-text">CATS AND DOGS</div>
      </div>
    </div>
  </div>
  <div class="features">
    <div class="container">
      <div class="row">
        <div class="col-md-6 feature">
        <span class="fa-stack fa-5x">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-paw fa-inverse fa-stack-1x"></i>
        </span>
          <h3>Animal Classification</h3>
          <p>This is a mini project about image classification to answering the input image is a dogor a cat with machine learning algorithm called convolutional neural networks</p>
        </div>
        <div class="col-md-6 feature">
        <span class="fa-stack fa-5x">
          <i class="fa fa-circle fa-stack-2x c-green"></i>
          <i class="fa fa-life-ring fa-inverse fa-stack-1x"></i>
        </span>
          <h3>Why choose us?</h3>
          <p>Fast, accurate, effective</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 feature">
        <span class="fa-stack fa-5x">
          <i class="fa fa-circle fa-stack-2x c-red"></i>
          <i class="fa fa-heart fa-inverse fa-stack-1x"></i>
        </span>
          <h3> Made for passion <3</h3>
        </div>
        <div class="col-md-6 feature">
        <span class="fa-stack fa-5x">
          <i class="fa fa-circle fa-stack-2x c-blue"></i>
          <i class="fa fa-facebook fa-inverse fa-stack-1x"></i>
        </span>
          <h3>Facebook</h3>
          <p> <a  href="https://www.facebook.com/marsudocac/"> Quốc Khánh</a></p>
            <p> <a  href="https://www.facebook.com/profile.php?id=100041848608717/">Minh Hoàng</a></p>
        </div>
      </div>
    </div>
  </div>
    <div class="footer hidden-print">
  <div class="footer-head">
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <h2 class="title-text">R.I.I.O</h2>
        </div>
        <div class="col-sm-6 text-right small-text">
           We &hearts; Animal
        </div>
      </div>
    </div>
  </div>
  <div class="footer-body">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h4 class="title-text">Address</h4>
          <p>Greenwich Of University (VietNam) </p>
        </div>
        <div class="col-md-4 text-center">
          <h4 class="title-text">Contact</h4>
          <ul class="list-unstyled">
            <li>
              <a href="mailto:contato@cademeubicho.com">contato@edith.com</a>
            </li>
          </ul>
        </div>
        <div class="col-md-4">
          <div class="fb-page" data-href="https://www.facebook.com/marsudocac/" data-small-header="true"
               data-adapt-container-width="true" data-hide-cover="true" data-show-facepile="true">
            <div class="fb-xfbml-parse-ignore">
              <blockquote cite="https://www.facebook.com/marsudocac">
                <a href="https://www.facebook.com/marsudocac">R.I.I.O LTD</a>
              </blockquote>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/ai/upload.html
<!DOCTYPE html>
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
{% load static %}
{% load crispy_forms_tags %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            <h1 class="mt-2 text-xl-center font-weight-bold display-3 bg-dark text-white">R.I.I.O</h1>
            <hr class="mt-0 mb-4">
            {% block show %}
                {% if image %}
                    <h3>{{ image.name }}</h3>
                    <img src="{{ image.image.url }}  "style="width:500px;high:500px;" alt="">
                {% endif %}
            {% endblock %}
            {% block content %}
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success" >Upload</button>
                    <a href="{% url 'ai:history' %}" class="btn btn-success" role="button" aria-pressed="true">History</a>
                    <a href="{% url 'ai:homepage' %}" class="btn btn-success" role="button" aria-pressed="true">Home</a>
                </form>
            {% endblock %}
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="{% static "js/bootstrap.bundle.js" %}"></script>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>R.I.I.O</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
</head>
<body>
<div class="navbar navbar-fixed-top navbar-home" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" >
        R.I.I.O
      </a>
    </div>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'ai:upload' %}">Upload</a></li>
        <li><a href="{% url 'ai:history' %}">History</a></li>
      </ul>
  </div>
</div>
{% block page %}{% endblock page %}
{% block show %}{% endblock show %}
{% block content %}{% endblock content %}
{% block history %}{% endblock history %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="{% static "js/bootstrap.bundle.js" %}"></script>
</body>
</html>